// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PractiseProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Feature1")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class Feature1Feature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Feature1", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "MainPage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MainPageContent - Chrome - inprivate")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task MainPageContent_Chrome_Inprivate()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MainPageContent - Chrome - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Choose button HomeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table45.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table45.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-98-868-63-63"});
                table45.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table45.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table45.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table45.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table45.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 8
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table45, "When ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDicribe"});
                table46.AddRow(new string[] {
                            "h5",
                            "Системи огорож",
                            "https://dimdvirdevelop.netlify.app/img/portfolio/pf1.jpg",
                            "true,true",
                            "false,true"});
                table46.AddRow(new string[] {
                            "h5",
                            "Покрівельні системи",
                            "https://tile.ua/wp-content/uploads/2023/02/x530yf530.jpg.pagespeed.ic.hvnFsQi7o_." +
                                "webp",
                            "true,true",
                            "false,true"});
                table46.AddRow(new string[] {
                            "h5",
                            "Металевий сайдинг на фасад",
                            "https://tile.ua/wp-content/uploads/2021/07/xmetalevyj-sajdynh-1.jpg.pagespeed.ic." +
                                "iCilFAWKtl.webp",
                            "true,true",
                            "false,true"});
                table46.AddRow(new string[] {
                            "h5",
                            "Водостічні системи",
                            "https://tile.ua/wp-content/uploads/2021/07/xPravylna-vodostichka.jpg.pagespeed.ic" +
                                ".C3TstMbhZO.webp",
                            "true,true",
                            "false,true"});
                table46.AddRow(new string[] {
                            "h5",
                            "Комплектуючі до покрівельних систем",
                            "https://tile.ua/wp-content/uploads/2023/10/xkomplektuiuch.jpg.pagespeed.ic.AIfVle" +
                                "-OQm.webp",
                            "true,true",
                            "false,true"});
#line 17
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table46, "And ");
#line hidden
#line 24
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MainPageContent - Edge - inprivate")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task MainPageContent_Edge_Inprivate()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MainPageContent - Edge - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
 await testRunner.GivenAsync("open page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
 await testRunner.AndAsync("Choose button HomeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table47.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table47.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-98-868-63-63"});
                table47.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table47.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table47.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table47.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table47.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 31
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table47, "When ");
#line hidden
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDicribe"});
                table48.AddRow(new string[] {
                            "h5",
                            "Системи огорож",
                            "https://dimdvirdevelop.netlify.app/img/portfolio/pf1.jpg",
                            "true,true",
                            "false,true"});
                table48.AddRow(new string[] {
                            "h5",
                            "Покрівельні системи",
                            "https://tile.ua/wp-content/uploads/2023/02/x530yf530.jpg.pagespeed.ic.hvnFsQi7o_." +
                                "webp",
                            "true,true",
                            "false,true"});
                table48.AddRow(new string[] {
                            "h5",
                            "Металевий сайдинг на фасад",
                            "https://tile.ua/wp-content/uploads/2021/07/xmetalevyj-sajdynh-1.jpg.pagespeed.ic." +
                                "iCilFAWKtl.webp",
                            "true,true",
                            "false,true"});
                table48.AddRow(new string[] {
                            "h5",
                            "Водостічні системи",
                            "https://tile.ua/wp-content/uploads/2021/07/xPravylna-vodostichka.jpg.pagespeed.ic" +
                                ".C3TstMbhZO.webp",
                            "true,true",
                            "false,true"});
                table48.AddRow(new string[] {
                            "h5",
                            "Комплектуючі до покрівельних систем",
                            "https://tile.ua/wp-content/uploads/2023/10/xkomplektuiuch.jpg.pagespeed.ic.AIfVle" +
                                "-OQm.webp",
                            "true,true",
                            "false,true"});
#line 40
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table48, "And ");
#line hidden
#line 47
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
