// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PractiseProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NavigationCheck")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class NavigationCheckFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "NavigationCheck", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NavigationCheck.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheck- Chrome")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task NavigationCheck_Chrome()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheck- Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Choose button HomeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table5.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table5.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table5.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table5.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table5.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/href",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table5.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table5.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table5.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 8
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table5, "When ");
#line hidden
#line 18
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheck- Edge - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheck_Edge_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheck- Edge - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
 await testRunner.GivenAsync("Choose button HomeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table6.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table6.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table6.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table6.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table6.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table6.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table6.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table6.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 22
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table6, "When ");
#line hidden
#line 32
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckAboutPage- Chrome - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckAboutPage_Chrome_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckAboutPage- Chrome - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
 await testRunner.GivenAsync("Choose button AboutUsButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table7.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table7.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table7.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table7.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table7.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table7.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table7.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table7.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 36
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table7, "When ");
#line hidden
#line 46
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckAboutPage- Edge - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckAboutPage_Edge_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckAboutPage- Edge - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
 await testRunner.GivenAsync("Choose button AboutUsButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table8.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table8.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table8.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table8.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table8.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table8.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table8.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table8.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 50
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table8, "When ");
#line hidden
#line 60
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckCatalogePage- Edge - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckCatalogePage_Edge_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckCatalogePage- Edge - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 64
 await testRunner.GivenAsync("Choose button CatalogeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table9.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table9.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table9.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table9.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table9.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table9.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table9.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table9.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 65
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table9, "When ");
#line hidden
#line 75
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckCatalogePage- Chrome - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckCatalogePage_Chrome_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckCatalogePage- Chrome - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
 await testRunner.GivenAsync("Choose button CatalogeButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table10.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table10.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table10.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table10.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table10.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table10.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table10.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table10.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 79
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table10, "When ");
#line hidden
#line 89
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckContactsPage- Edge - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckContactsPage_Edge_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckContactsPage- Edge - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
 await testRunner.GivenAsync("Choose button ContactsButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table11.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table11.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table11.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table11.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table11.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table11.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table11.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table11.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 93
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table11, "When ");
#line hidden
#line 103
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("NavigationCheckContactsPage- Chrome - inprivate")]
        public async global::System.Threading.Tasks.Task NavigationCheckContactsPage_Chrome_Inprivate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NavigationCheckContactsPage- Chrome - inprivate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 106
 await testRunner.GivenAsync("Choose button ContactsButton in navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "isDisplayed",
                            "text",
                            "link"});
                table12.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "true,true",
                            "",
                            "img/logo.jpg"});
                table12.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "true,true",
                            "380-98-868-63-63",
                            ""});
                table12.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table12.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "true,true",
                            "",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table12.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "/home",
                            "a",
                            "href",
                            "true,true",
                            "Головна",
                            ""});
                table12.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "/about-us",
                            "a",
                            "href",
                            "true,true",
                            "Про нас",
                            ""});
                table12.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "/portfolio-gallery",
                            "a",
                            "href",
                            "true,true",
                            "Каталог наших робіт",
                            ""});
                table12.AddRow(new string[] {
                            "Contacts",
                            "buttonCheck",
                            "/contact-us",
                            "a",
                            "href",
                            "true,true",
                            "Контакти",
                            ""});
#line 107
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table12, "When ");
#line hidden
#line 117
 await testRunner.ThenAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
