// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PractiseProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ProductionCheck")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ProductionCheckFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "ProductionCheck", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductionCheck.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckFirstProductionCatalog - Chrome")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task CheckFirstProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckFirstProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Choose one of Production1 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDicribe"});
                table13.AddRow(new string[] {
                            "h2",
                            "Жалюзі класичні",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product1Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "Жалюзі STANDART",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product2Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "Жалюзі РОМБ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product3Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "Жалюзі ЛЕГО",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product4Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО РОМБ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product5Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО PIPE L",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product6Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО PIPE XL",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product7Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПРЯМЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product8Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПРЯМЕ STRONG",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product9Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПІВКРУГЛЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product10Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО ФІГУРНЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product11Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО ФІГУРНЕ 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product12Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО РІЗНОШИРИННЕ ПІВКРУГЛЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product13Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО КОСЕ З ПРОМІЖКОМ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product14Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "РАНЧО КОСЕ БЕЗ ПРОМІЖКУ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product15Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ТВІНГО КЛАСИЧНЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product16Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ТВІНГО ПРЯМЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product17Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ТВІНГО DUOS",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product18Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 170 мм",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product19Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 170 мм 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product20Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 225 мм",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product21Photo1.png",
                            "true,true",
                            "false,true"});
                table13.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 225 мм 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product22Photo1.png",
                            "true,true",
                            "false,true"});
#line 8
 await testRunner.WhenAsync("check ourProductionSection", ((string)(null)), table13, "When ");
#line hidden
#line 32
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckSecondProductionCatalog - Chrome")]
        public async global::System.Threading.Tasks.Task CheckSecondProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckSecondProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
 await testRunner.GivenAsync("Choose one of Production2 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDiscribe"});
                table14.AddRow(new string[] {
                            "h2",
                            "Фальц-настил",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product1Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Фальц КЛАСИКА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product2Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Фальц ТРАПЕЦІЯ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product3Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Фальц ХВИЛЯ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product4Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Клік Фальц ПРЕМІУМ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product5Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Клік Фальц СМАРТ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product6Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил СИНУСОЇДА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product7Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил С-8",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product8Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил C-14",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product9Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил H-14",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product10Photo1%20(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил H-20",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product11Photo1(1).png",
                            "true,true",
                            "true,true"});
                table14.AddRow(new string[] {
                            "h2",
                            "Профнастил C-20",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product12Photo1(1).png",
                            "true,true",
                            "true,true"});
#line 37
 await testRunner.WhenAsync("check ourProductionSection", ((string)(null)), table14, "When ");
#line hidden
#line 52
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
