// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PractiseProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ProductionCheck")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ProductionCheckFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "ProductionCheck", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ProductionCheck.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckFirstProductionCatalog - Chrome")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task CheckFirstProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckFirstProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Choose one of Production1 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table57.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table57.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-9868-63-63"});
                table57.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table57.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table57.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table57.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table57.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 8
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table57, "When ");
#line hidden
                global::Reqnroll.Table table58 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDicribe"});
                table58.AddRow(new string[] {
                            "h2",
                            "Жалюзі класичні",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product1Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "Жалюзі STANDART",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product2Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "Жалюзі РОМБ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product3Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "Жалюзі ЛЕГО",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product4Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО РОМБ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product5Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО PIPE L",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product6Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО PIPE XL",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product7Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПРЯМЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product8Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПРЯМЕ STRONG",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product9Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО ПІВКРУГЛЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product10Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО ФІГУРНЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product11Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО ФІГУРНЕ 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product12Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО РІЗНОШИРИННЕ ПІВКРУГЛЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product13Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО КОСЕ З ПРОМІЖКОМ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product14Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "РАНЧО КОСЕ БЕЗ ПРОМІЖКУ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product15Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ТВІНГО КЛАСИЧНЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product16Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ТВІНГО ПРЯМЕ",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product17Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ТВІНГО DUOS",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product18Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 170 мм",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product19Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 170 мм 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product20Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 225 мм",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product21Photo1.png",
                            "true,true",
                            "false,true"});
                table58.AddRow(new string[] {
                            "h2",
                            "ГОРИЗОНТ 225 мм 2-ст",
                            "https://dimdvirdevelop.netlify.app/img/category02/Product22Photo1.png",
                            "true,true",
                            "false,true"});
#line 17
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table58, "And ");
#line hidden
#line 41
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckSecondProductionCatalog - Chrome")]
        public async global::System.Threading.Tasks.Task CheckSecondProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckSecondProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
 await testRunner.GivenAsync("Choose one of Production2 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table59 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table59.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table59.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-98-868-63-63"});
                table59.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table59.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table59.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table59.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table59.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 46
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table59, "When ");
#line hidden
                global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDiscribe"});
                table60.AddRow(new string[] {
                            "h2",
                            "Фальц-настил",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product1Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Фальц КЛАСИКА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product2Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Фальц ТРАПЕЦІЯ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product3Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Фальц ХВИЛЯ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product4Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Клік Фальц ПРЕМІУМ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product5Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Клік Фальц СМАРТ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product6Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил СИНУСОЇДА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product7Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил С-8",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product8Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил C-14",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product9Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил H-14",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product10Photo1%20(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил H-20",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product11Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил C-20",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product12Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил 20",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product13Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил HC-35",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product14Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил HC-45",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product15Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил HC-57",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product16Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил HC-92",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product17Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил 135",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product18Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т07",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product19Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т14",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product20Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т18",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product21Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т18 стіновий",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product22Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т40",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product23Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Профнастил Т57",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product24Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ЕЛЕГАНТ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product25Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МАДЕРА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product26Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МАДЕРА модульна",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product27Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ЕЛІТ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product28Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця РЕТРО ПРЕМІУМ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product29Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МОНТЕРЕЙ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product30Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МОДЕРН",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product31Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ЕРА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product32Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ЕРА модульна",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product33Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ПРЕМІУМ",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product34Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ІНТЕГРА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product35Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ІНТЕГРА модульна",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product36Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця РЕТРО",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product37Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ВЕНЕРА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product38Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця ВЕНЕРА модульна",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product39Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця КЛАСИКА",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product40Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МОДЕРН (будсервіс)",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product41Photo1(1).png",
                            "true,true",
                            "true,true"});
                table60.AddRow(new string[] {
                            "h2",
                            "Металочерепиця МОДЕРН модульна",
                            "https://dimdvirdevelop.netlify.app/img/category01/Product42Photo1(1).png",
                            "true,true",
                            "true,true"});
#line 55
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table60, "And ");
#line hidden
#line 99
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckThirdProductionCatalog - Chrome")]
        public async global::System.Threading.Tasks.Task CheckThirdProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckThirdProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
 await testRunner.GivenAsync("Choose one of Production3 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table61.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table61.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-98-868-63-63"});
                table61.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.instagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table61.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table61.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table61.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table61.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 104
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table61, "When ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDiscribe"});
                table62.AddRow(new string[] {
                            "h2",
                            "Блок-хаус",
                            "https://dimdvirdevelop.netlify.app/img/category04/product01.png",
                            "true,true",
                            "false,true"});
                table62.AddRow(new string[] {
                            "h2",
                            "Сайдинг",
                            "https://dimdvirdevelop.netlify.app/img/category04/product02.png",
                            "true,true",
                            "false,true"});
                table62.AddRow(new string[] {
                            "h2",
                            "Фасадна панель",
                            "https://dimdvirdevelop.netlify.app/img/category04/product03.png",
                            "true,true",
                            "false,true"});
#line 113
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table62, "And ");
#line hidden
#line 118
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckFourthProductionCatalog - Chrome")]
        public async global::System.Threading.Tasks.Task CheckFourthProductionCatalog_Chrome()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckFourthProductionCatalog - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 122
 await testRunner.GivenAsync("Choose one of Production5 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "OptionName",
                            "method",
                            "valueName",
                            "valueType",
                            "elementType",
                            "compareType",
                            "isDisplayed",
                            "compareData"});
                table63.AddRow(new string[] {
                            "Logo",
                            "pictureCheck",
                            "Дім-Двір",
                            "img",
                            "alt",
                            "src",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/img/logo.jpg"});
                table63.AddRow(new string[] {
                            "Phone-number",
                            "textCheck",
                            "navbar-text",
                            "span",
                            "class",
                            "textContent",
                            "true,true",
                            "380-98-868-63-63"});
                table63.AddRow(new string[] {
                            "Instagram-icon",
                            "iconCheck",
                            "icon1",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.insagram.com/dim_dvir?igsh=MTdtZWlvZWFqNDF3Nw%3D%3D&utm_source=qr"});
                table63.AddRow(new string[] {
                            "facebook-icon",
                            "iconCheck",
                            "icon2",
                            "a",
                            "id",
                            "href",
                            "true,true",
                            "https://www.facebook.com/share/1C7ca43qC7"});
                table63.AddRow(new string[] {
                            "HomeButton",
                            "buttonCheck",
                            "Головна",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/home"});
                table63.AddRow(new string[] {
                            "AboutButton",
                            "buttonCheck",
                            "Про нас",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/about-us"});
                table63.AddRow(new string[] {
                            "Catalog",
                            "buttonCheck",
                            "Каталог наших робіт",
                            "a",
                            "textContent",
                            "href",
                            "true,true",
                            "https://dimdvirdevelop.netlify.app/portfolio-gallery"});
#line 123
 await testRunner.WhenAsync("Check all components in navigation", ((string)(null)), table63, "When ");
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "elementType",
                            "text",
                            "photoLink",
                            "isDisplayed",
                            "isDiscribe"});
                table64.AddRow(new string[] {
                            "h2",
                            "Коньок фігурний",
                            "https://dimdvirdevelop.netlify.app/img/category03/product01.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Коньок універсальний",
                            "https://dimdvirdevelop.netlify.app/img/category03/product02.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Коньок плоский",
                            "https://dimdvirdevelop.netlify.app/img/category03/product03.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Коньок декоративний",
                            "https://dimdvirdevelop.netlify.app/img/category03/product04.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Коньок трикутний",
                            "https://dimdvirdevelop.netlify.app/img/category03/product05.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Заглушка конька",
                            "https://dimdvirdevelop.netlify.app/img/category03/product06.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Снігозатримувач",
                            "https://dimdvirdevelop.netlify.app/img/category03/product07.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Снігозатримувач трубчастий для фальцу",
                            "https://dimdvirdevelop.netlify.app/img/category03/product08.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Снігозатримувач трубчастий для Фальц-настилу",
                            "https://dimdvirdevelop.netlify.app/img/category03/product09.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Снігоріз",
                            "https://dimdvirdevelop.netlify.app/img/category03/product10.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Снігозатримувач півмісяць",
                            "https://dimdvirdevelop.netlify.app/img/category03/product11.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Стінний захист з зарізом",
                            "https://dimdvirdevelop.netlify.app/img/category03/product12.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Стінний захист",
                            "https://dimdvirdevelop.netlify.app/img/category03/product13.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Захист карнизу",
                            "https://dimdvirdevelop.netlify.app/img/category03/product14.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Вітрозахист",
                            "https://dimdvirdevelop.netlify.app/img/category03/product15.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Вітрозахист для підшивки",
                            "https://dimdvirdevelop.netlify.app/img/category03/product16.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Вітрозахист фігурний",
                            "https://dimdvirdevelop.netlify.app/img/category03/product17.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Жолоб плоский",
                            "https://dimdvirdevelop.netlify.app/img/category03/product18.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Накладка жолоба",
                            "https://dimdvirdevelop.netlify.app/img/category03/product19.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Планка зашивки універсальна",
                            "https://dimdvirdevelop.netlify.app/img/category03/product20.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Планка зашивки з відливом",
                            "https://dimdvirdevelop.netlify.app/img/category03/product21.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Планка зашивки",
                            "https://dimdvirdevelop.netlify.app/img/category03/product22.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Закоменева планка",
                            "https://dimdvirdevelop.netlify.app/img/category03/product23.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Кутник зовнішній",
                            "https://dimdvirdevelop.netlify.app/img/category03/product24.png",
                            "true,true",
                            "false,true"});
                table64.AddRow(new string[] {
                            "h2",
                            "Кутник внутрішній",
                            "https://dimdvirdevelop.netlify.app/img/category03/product25.png",
                            "",
                            ""});
#line 132
 await testRunner.AndAsync("check ourProductionSection", ((string)(null)), table64, "And ");
#line hidden
#line 159
 await testRunner.ThenAsync("compare data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 160
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
