// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PractiseProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SecondProductCheckink")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SecondProductCheckinkFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "SecondProductCheckink", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SecondProductCheckink.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CheckProduct1 - Chrome")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task CheckProduct1_Chrome()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CheckProduct1 - Chrome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Choose one of Production3 in section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("select Product1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "textContent"});
                table65.AddRow(new string[] {
                            "total_width",
                            "395"});
                table65.AddRow(new string[] {
                            "width",
                            "357"});
                table65.AddRow(new string[] {
                            "lenght",
                            "3000"});
#line 9
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table65, "And ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "src"});
                table66.AddRow(new string[] {
                            "photo_main",
                            "https://dimdvirdevelop.netlify.app/img/category04/product01.png"});
                table66.AddRow(new string[] {
                            "photo_drawing",
                            "https://dimdvirdevelop.netlify.app/img/category04/product0102.png"});
#line 15
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table66, "And ");
#line hidden
#line 19
 await testRunner.ThenAsync("compare data for product", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
 await testRunner.GivenAsync("go back", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
 await testRunner.WhenAsync("select Product2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "textContent"});
                table67.AddRow(new string[] {
                            "total_width",
                            "265"});
                table67.AddRow(new string[] {
                            "width",
                            "231"});
                table67.AddRow(new string[] {
                            "lenght",
                            "3000"});
#line 23
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table67, "And ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "src"});
                table68.AddRow(new string[] {
                            "photo_main",
                            "https://dimdvirdevelop.netlify.app/img/category04/product02.png"});
                table68.AddRow(new string[] {
                            "photo_drawing",
                            "https://dimdvirdevelop.netlify.app/img/category04/product0202.png"});
#line 29
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table68, "And ");
#line hidden
#line 33
 await testRunner.ThenAsync("compare data for product", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
 await testRunner.GivenAsync("go back", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
 await testRunner.WhenAsync("select Product3", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "textContent"});
                table69.AddRow(new string[] {
                            "total_width",
                            "376"});
                table69.AddRow(new string[] {
                            "width",
                            "340"});
                table69.AddRow(new string[] {
                            "lenght",
                            "3000"});
#line 37
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table69, "And ");
#line hidden
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "src"});
                table70.AddRow(new string[] {
                            "photo_main",
                            "https://dimdvirdevelop.netlify.app/img/category04/product03.png"});
                table70.AddRow(new string[] {
                            "photo_drawing",
                            "https://dimdvirdevelop.netlify.app/img/category04/product0302.png"});
#line 43
 await testRunner.AndAsync("check product\'s properties", ((string)(null)), table70, "And ");
#line hidden
#line 47
 await testRunner.ThenAsync("compare data for product", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
 await testRunner.AndAsync("close browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
